const qoutes = [
  { id: 1, text: `You have power over your mind not outside events. Realize this and you will find strength`, author: "Marcus Aurelius" },
  { id: 2, text: `He who fears death will never do anything worthy of a man who is alive.`, author: "Seneca" },
  { id: 3, text: `Vanity of vanity is all vanities`, author: "Ecclesiastes" },
  { id: 4, text: `Without music, life would be a mistake.`, author: "Nietzsche" },
  { id: 5, text: `The soul becomes dyed with the color of its thoughts.`, author: "Marcus Aurelius" },
  { id: 6, text: `First say to yourself what you would be; and then do what you have to do.`, author: "Epictetus" },
  { id: 7, text: `We suffer more often in imagination than in reality.`, author: "Seneca" },
  { id: 8, text: `The best revenge is not to be like your enemy.`, author: "Marcus Aurelius" },
  { id: 9, text: `Men are disturbed not by things, but by the views they take of them.`, author: "Epictetus" },
  { id: 10, text: `The obstacle is the way.`, author: "Marcus Aurelius" },
  { id: 11, text: `Luck is what happens when preparation meets opportunity.`, author: "Seneca" },
  { id: 12, text: `It is not what happens to you, but how you react to it that matters.`, author: "Epictetus" },
  { id: 13, text: `When you arise in the morning, think of what a precious privilege it is to be alive.`, author: "Marcus Aurelius" },
  { id: 14, text: `Difficulties strengthen the mind, as labor does the body.`, author: "Seneca" },
  { id: 15, text: `No man is free who is not master of himself.`, author: "Epictetus" },
  { id: 16, text: `Very little is needed to make a happy life; it is all within yourself, in your way of thinking.`, author: "Marcus Aurelius" },
  { id: 17, text: `If you have a garden and a library, you have everything you need.`, author: "Epictetus" },
  { id: 18, text: `The greatest wealth is to live content with little.`, author: "Seneca" },
  { id: 19, text: `The happiness of your life depends upon the quality of your thoughts.`, author: "Marcus Aurelius" },
  { id: 20, text: `This life is short and time demands its due.`, author: "Marcus Aurelius" },
  { id: 21, text: `The key is to keep company only with people who uplift you, whose presence calls forth your best.`, author: "Epictetus" },
  { id: 22, text: `A person who never made a mistake never tried anything new.`, author: "Seneca" },
  { id: 23, text: `If it is not right, do not do it; if it is not true, do not say it.`, author: "Marcus Aurelius" },
  { id: 24, text: `Circumstances don't make a man, they reveal him.`, author: "Epictetus" },
  { id: 25, text: `All cruelty springs from weakness.`, author: "Seneca" },
  { id: 26, text: `Do not spoil what you have by desiring what you have not.`, author: "Marcus Aurelius" },
  { id: 27, text: `Set your heart on doing good. Do not think of anything else.`, author: "Epictetus" },
  { id: 28, text: `The soul is dyed by its thoughts.`, author: "Marcus Aurelius" },
  { id: 29, text: `There is no man so poor who has not something to give.`, author: "Epictetus" },
  { id: 30, text: `Look well into thyself; there is a source of strength that will always spring up if thou wilt always search.`, author: "Marcus Aurelius" },
  { id: 31, text: `It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.`, author: "Epictetus" },
  { id: 32, text: `While we are postponing, life speeds by.`, author: "Seneca" },
  { id: 33, text: `You are what you do when you do not have to do anything.`, author: "Marcus Aurelius" },
  { id: 34, text: `A man's character will make itself known in the pressure of circumstances.`, author: "Seneca" },
  { id: 35, text: `The universe is change; life is opinion.`, author: "Marcus Aurelius" },
  { id: 36, text: `Make sure your mind is not the least bit following anything but the truth.`, author: "Epictetus" },
  { id: 37, text: `The bravest soul is the one who is not afraid to hear the truth.`, author: "Seneca" },
  { id: 38, text: `Do not be distracted by the clamor of the world.`, author: "Marcus Aurelius" },
  { id: 39, text: `No one is free from suffering or fear or whatever may happen.`, author: "Epictetus" },
  { id: 40, text: `The time will come when men will be judged for their thoughts.`, author: "Seneca" },
  { id: 41, text: `The best way to avenge yourself is to be unlike him who injured you.`, author: "Marcus Aurelius" },
  { id: 42, text: `We should all be wise enough to know that there are things no one can control.`, author: "Seneca" },
  { id: 43, text: `The man who has no opinion of his own cannot be happy.`, author: "Marcus Aurelius" },
  { id: 44, text: `If it is not possible to live without some pain, then live with dignity, and do not complain.`, author: "Epictetus" },
  { id: 45, text: `It is the quality of the life, not the length, that matters.`, author: "Seneca" },
  { id: 46, text: `Nothing is enough for the man to whom enough is too little.`, author: "Marcus Aurelius" },
  { id: 47, text: `There are two ways of seeing: by the standard of the body and by the standard of the mind.`, author: "Epictetus" },
  { id: 48, text: `No one can give you a better life than you can create.`, author: "Seneca" },
  { id: 49, text: `To be yourself is to be your own master.`, author: "Marcus Aurelius" },
  { id: 50, text: `The world is not a place to survive; it is a place to live.`, author: "Epictetus" },
  { id: 51, text: `The wise man does not become prey to the crowd.`, author: "Seneca" },
  { id: 52, text: `The only wealth which you will keep forever is the wealth you have given away.`, author: "Marcus Aurelius" },
  { id: 53, text: `Happiness and freedom begin with a clear understanding of one principle: some things are within your control, and some things are not.`, author: "Epictetus" },
  { id: 54, text: `If a man knows not which port he sails, no wind is favorable.`, author: "Marcus Aurelius" },
  { id: 55, text: `Do not pray for an easy life, pray for the strength to endure a difficult one.`, author: "Epictetus" },
  { id: 56, text: `We are all more or less the prisoners of our own minds.`, author: "Seneca" },
  { id: 57, text: `Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.`, author: "Marcus Aurelius" },
  { id: 58, text: `You are capable of doing what the wise are capable of doing.`, author: "Epictetus" },
  { id: 59, text: `The more we value things outside our control, the less control we have.`, author: "Seneca" },
  { id: 60, text: `A person's worth is measured by how much they can endure.`, author: "Marcus Aurelius" },
  { id: 61, text: `Of all existing things capable of being transferred, the most valuable is the trained soul.`, author: "Epictetus" },
  { id: 62, text: `It is not that we have a short time to live, but that we waste a lot of it.`, author: "Seneca" },
  { id: 63, text: `Don't let your mind wander to what might have been. It can't return and itself is not such a treasure.`, author: "Marcus Aurelius" },
  { id: 64, text: `If you want to improve, be content to be thought foolish and stupid.`, author: "Epictetus" },
  { id: 65, text: `It is not a lack of love, but a lack of friendship that makes unhappy marriages.`, author: "Seneca" },
  { id: 66, text: `The soul is not harmed by the hardness of life but by the softness of its own thoughts.`, author: "Marcus Aurelius" },
  { id: 67, text: `He who has a why to live can bear almost any how.`, author: "Epictetus" },
  { id: 68, text: `The greatest part of your life will be spent in the effort to remain free.`, author: "Seneca" },
  { id: 69, text: `When another blames you or hates you, or people voice similar things, go to your inner self, explore, and you will find strength.`, author: "Marcus Aurelius" },
  { id: 70, text: `The shortest answer to the question: what should we do? is: what is right?`, author: "Epictetus" },
  { id: 71, text: `The man who is good will make himself worthy of trust.`, author: "Seneca" },
  { id: 72, text: `The universe is full of things that are beyond our control.`, author: "Marcus Aurelius" },
  { id: 73, text: `We all have a tendency to believe what we want to believe.`, author: "Epictetus" },
  { id: 74, text: `The world is neither fair nor unfair; it is simply a world.`, author: "Seneca" },
  { id: 75, text: `Be tolerant with others and strict with yourself.`, author: "Marcus Aurelius" },
  { id: 76, text: `The more you know, the more you realize you know nothing.`, author: "Epictetus" },
  { id: 77, text: `The one thing we can be sure of is the uncertainty of life.`, author: "Seneca" },
  { id: 78, text: `Your life is what your thoughts make it.`, author: "Marcus Aurelius" },
  { id: 79, text: `Only the educated are free.`, author: "Epictetus" },
  { id: 80, text: `The wise person adapts to circumstances, while a fool tries to force them.`, author: "Seneca" },
  { id: 81, text: `Choose not to be harmed—and you won’t feel harmed.`, author: "Marcus Aurelius" },
  { id: 82, text: `A ship should not be directed by the waves.`, author: "Epictetus" },
  { id: 83, text: `It is not in the stars to hold our destiny but in ourselves.`, author: "Seneca" },
  { id: 84, text: `When you are offended, think of how much you have been forgiven.`, author: "Marcus Aurelius" },
  { id: 85, text: `The mind is not just a spectator; it is an active participant in all that happens.`, author: "Epictetus" },
  { id: 86, text: `We must become more disciplined in our thoughts if we want less fear.`, author: "Seneca" },
  { id: 87, text: `No one can keep you from your purpose except yourself.`, author: "Marcus Aurelius" },
  { id: 88, text: `If you are pained by external things, it is not they that disturb you, but your judgment of them.`, author: "Epictetus" },
  { id: 89, text: `The only way to peace is to stop trying to own the world.`, author: "Seneca" },
  { id: 90, text: `The best perfumes are those of humble thoughts.`, author: "Marcus Aurelius" },
  { id: 91, text: `Your tranquility is not in your possessions but in your mind.`, author: "Epictetus" },
  { id: 92, text: `The more you narrow your appetite, the more you expand your freedom.`, author: "Seneca" },
  { id: 93, text: `Waste no more time arguing what a good man should be. Be one.`, author: "Marcus Aurelius" },
  { id: 94, text: `To be free is to be able to choose what is good.`, author: "Epictetus" },
  { id: 95, text: `The wise are not moved by the opinions of the crowd.`, author: "Seneca" },
  { id: 96, text: `When things go wrong, be patient and remember this is all part of the lesson.`, author: "Marcus Aurelius" },
  { id: 97, text: `I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'`, author: "Muhammad Ali" },
  { id: 98, text: `You have to expect things of yourself before you can do them.`, author: "Michael Jordan" },
  { id: 99, text: `Everyone has a plan until they get punched in the mouth.`, author: "Mike Tyson" },
  { id: 100, text: `Tough times don't last, tough people do.`, author: "Serena Williams" },
  { id: 101, text: `The most important thing is to try and inspire people so that they can be great in whatever they want to do.`, author: "Kobe Bryant" },
  { id: 102, text: `Success is not final, failure is not fatal: it is the courage to continue that counts.`, author: "Tom Brady" },
  { id: 103, text: `The more I practice, the luckier I get.`, author: "Tiger Woods" },
  { id: 104, text: `You may not control all the events that happen to you, but you can decide not to be reduced by them.`, author: "Maya Angelou" },
  { id: 105, text: `It always seems impossible until it's done.`, author: "Nelson Mandela" },
  { id: 106, text: `Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.`, author: "Steve Jobs" },
  { id: 107, text: `Success isn't always about greatness. It's about consistency. Consistent hard work gains success. Greatness will come.`, author: "Dwayne Johnson" },
  { id: 108, text: `Stay hard.`, author: "David Goggins" },
  { id: 109, text: `Do not pray for an easy life, pray for the strength to endure a difficult one.`, author: "Bruce Lee" },
  { id: 110, text: `Discipline is choosing between what you want most and what you want now.`, author: "Jim Stovall" },
  { id: 111, text: `You can't be afraid to fail. It's the only way you succeed.`, author: "LeBron James" },
  { id: 112, text: `Dreams are not what you see in sleep, dreams are the things that do not let you sleep.`, author: "Cristiano Ronaldo" },
  { id: 113, text: `You miss 100% of the shots you don't take.`, author: "Wayne Gretzky" },
  { id: 114, text: `I trained, I feared nothing, and I knew what I wanted.`, author: "Usain Bolt" },
  { id: 115, text: `Discipline equals freedom.`, author: "Jocko Willink" },
  { id: 116, text: `Fortune favors the bold, but discipline keeps it.`, author: "Naval Ravikant" },
  { id: 117, text: `I think it is possible for ordinary people to choose to be extraordinary.`, author: "Elon Musk" },
  { id: 118, text: `Success is peace of mind, which is a direct result of self-satisfaction in knowing you did your best.`, author: "John Wooden" },
  { id: 119, text: `I am not afraid of storms, for I am learning how to sail my ship.`, author: "Abraham Lincoln" },
  { id: 120, text: `You do not rise to the level of your goals. You fall to the level of your systems.`, author: "James Clear" },
  { id: 121, text: `The only impossible journey is the one you never begin.`, author: "Tony Robbins" },
  { id: 122, text: `The harder the struggle, the more glorious the triumph.`, author: "Tim Grover" },
  { id: 123, text: `You cannot escape the responsibility of tomorrow by evading it today.`, author: "Jordan Peterson" },
  { id: 124, text: `The obstacle in the path becomes the path. Never forget, within every obstacle is an opportunity to improve our condition.`, author: "Ryan Holiday" },
  { id: 125, text: `I'm not going to be defined by a loss.`, author: "Kevin Durant" },
  { id: 126, text: `Good things come from hard work and perseverance.`, author: "Novak Djokovic" },
  { id: 127, text: `Tough times are a given, but tough people are not.`, author: "Roger Federer" },
  { id: 128, text: `Never give up, never surrender.`, author: "Rafael Nadal" },
  { id: 129, text: `To be successful, you have to take risks and be willing to fail.`, author: "Manny Pacquiao" },
  { id: 130, text: `I'm not scared to work. I'm not scared to put in the effort.`, author: "Floyd Mayweather" },
  { id: 131, text: `The beginning of love is the will to let those we love be perfectly themselves.`, author: "Thomas Merton" },
  { id: 132, text: `The privilege of a lifetime is to become who you truly are.`, author: "Carl Jung" },
  { id: 133, text: `We are what we repeatedly do. Excellence, then, is not an act, but a habit.`, author: "Aristotle" },
  { id: 134, text: `The first and greatest victory is to conquer yourself.`, author: "Plato" },
  { id: 135, text: `Our greatest glory is not in never falling, but in rising every time we fall.`, author: "Confucius" },
  { id: 136, text: `A journey of a thousand miles begins with a single step.`, author: "Lao Tzu" },
  { id: 137, text: `Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.`, author: "Sun Tzu" },
  { id: 138, text: `The unexamined life is not worth living.`, author: "Socrates" },
  { id: 139, text: `Courage is grace under pressure.`, author: "Ernest Hemingway" },
  { id: 140, text: `What lies behind us and what lies before us are tiny matters compared to what lies within us.`, author: "Ralph Waldo Emerson" },
  { id: 141, text: `Success usually comes to those who are too busy to be looking for it.`, author: "Henry David Thoreau" },
  { id: 142, text: `Pain is inevitable. Suffering is optional.`, author: "Haruki Murakami" },
  { id: 143, text: `Not everything that is faced can be changed, but nothing can be changed until it is faced.`, author: "James Baldwin" },
  { id: 144, text: `Life is like riding a bicycle. To keep your balance, you must keep moving.`, author: "Albert Einstein" },
  { id: 145, text: `Success is stumbling from failure to failure with no loss of enthusiasm.`, author: "Winston Churchill" },
  { id: 146, text: `It is not the critic who counts, but the man in the arena.`, author: "Teddy Roosevelt" },
  { id: 147, text: `The mind is everything. What you think you become.`, author: "Buddha" },
  { id: 148, text: `The wound is the place where the Light enters you.`, author: "Rumi" },
  { id: 149, text: `Be the change you wish to see in the world.`, author: "Mahatma Gandhi" },
  { id: 150, text: `If you judge people, you have no time to love them.`, author: "Mother Teresa" },
  { id: 151, text: `To win, you have to run your own race.`, author: "Steve Prefontaine" },
  { id: 152, text: `Work and sacrifice are the keys to success.`, author: "Kyrie Irving" },
  { id: 153, text: `You don't become a champion by accident.`, author: "Carmelo Anthony" },
  { id: 154, text: `You can't train to lose.`, author: "Anthony Joshua" },
  { id: 155, text: `The body can break, but the will must not.`, author: "Khabib Nurmagomedov" },
  { id: 156, text: `Amateurs sit and wait for inspiration; the rest of us just get up and go to work.`, author: "Stephen King" },
  { id: 157, text: `Success is a lousy teacher. It seduces smart people into thinking they can't lose.`, author: "Bill Gates" },
  { id: 158, text: `Work like there is someone working 24 hours a day to take it away from you.`, author: "Mark Cuban" },
  { id: 159, text: `The toughest opponent you'll ever face is your own mind.`, author: "Ray Lewis" },
  { id: 160, text: `I can't afford to be comfortable because I'm not trying to be comfortable; I'm trying to be great.`, author: "Derek Jeter" },
  { id: 161, text: `It ain't over till it's over.`, author: "Yogi Berra" },
  { id: 162, text: `Every strike brings me closer to the next home run.`, author: "Babe Ruth" },
  { id: 163, text: `Success is where preparation and opportunity meet.`, author: "Mia Hamm" },
  { id: 164, text: `You can't put a limit on anything. The more you dream, the farther you get.`, author: "Michael Phelps" },
  { id: 165, text: `The one thing I know for sure: I'm not going to quit.`, author: "Shaquille O’Neal" },
  { id: 166, text: `You can't win by yourself; you need the team.`, author: "Magic Johnson" },
  { id: 167, text: `The more I play, the easier it gets.`, author: "Larry Bird" },
  { id: 168, text: `Success is not because of the technology, but because of the people behind it.`, author: "Sundar Pichai" },
  { id: 169, text: `What we need to do is always lean into the future; when the world changes around you, and it does, you need to be ready.`, author: "Jeff Bezos" },
  { id: 170, text: `Our industry does not respect tradition. It only respects innovation.`, author: "Satya Nadella" },
  { id: 171, text: `The best way to predict the future is to create it.`, author: "Reid Hoffman" },
  { id: 172, text: `Don't be afraid to be disciplined. That's the path to greatness.`, author: "Eliud Kipchoge" },
  { id: 173, text: `Power is not in the tears of men, but in their ability to rise.`, author: "Frederick Douglass" },
  { id: 174, text: `Every great dream begins with a dreamer.`, author: "Harriet Tubman" },
  { id: 175, text: `Nothing in life is to be feared, it is only to be understood.`, author: "Marie Curie" },
  { id: 176, text: `If I have seen further, it is by standing on the shoulders of giants.`, author: "Isaac Newton" },
  { id: 177, text: `It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.`, author: "Charles Darwin" },
  { id: 178, text: `The hardest thing to do is to be yourself in a world where everyone is trying to make you be somebody else.`, author: "Oprah Winfrey" },
  { id: 179, text: `A man who stands for nothing will fall for anything.`, author: "Malcolm X" },
  { id: 180, text: `The time is always right to do what is right.`, author: "Martin Luther King Jr." },
  { id: 181, text: `You must never be fearful about what you are doing when it is right.`, author: "Rosa Parks" },
  { id: 182, text: `The question isn't who is going to let me; it's who is going to stop me.`, author: "Ayn Rand" },
  { id: 183, text: `Your life is your art. Make it a masterpiece.`, author: "Khalil Gibran" },
  { id: 184, text: `The best way to make children good is to make them happy.`, author: "Voltaire" },
  { id: 185, text: `The root of suffering is attachment.`, author: "Buddha" },
  { id: 186, text: `When we are no longer able to change a situation, we are challenged to change ourselves.`, author: "Viktor Frankl" },
  { id: 187, text: `You don't have to be great to start, but you have to start to be great.`, author: "Zig Ziglar" },
  { id: 188, text: `Never mistake activity for achievement.`, author: "John Wooden" },
  { id: 189, text: `Discipline is what separates the good from the great.`, author: "Nick Saban" },
  { id: 190, text: `The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.`, author: "Peyton Manning" },
  { id: 191, text: `I've failed over and over and over again in my life and that is why I succeed.`, author: "Michael Jordan" },
  { id: 192, text: `It's not bragging if you can back it up.`, author: "Muhammad Ali" },
  { id: 193, text: `You cannot control what other people do, but you can control how you respond.`, author: "Steve Harvey" },
  { id: 194, text: `You are not a victim of your circumstances; you are a creator of your future.`, author: "Seth Godin" },
  { id: 195, text: `Good is the enemy of great.`, author: "Jim Collins" },
  { id: 196, text: `You don't have to be perfect to be a good leader; you just have to keep moving.`, author: "Barack Obama" },
  { id: 197, text: `Courage starts with showing up and letting ourselves be seen.`, author: "Brené Brown" },
  { id: 198, text: `If you want to change the world, start off by making your bed.`, author: "Admiral William H. McRaven" },
  { id: 199, text: `I'm not afraid of being different, I'm proud of it.`, author: "Megan Rapinoe" },
  { id: 200, text: `Fight for the things that you care about, but do it in a way that will lead others to join you.`, author: "Ruth Bader Ginsburg" },
  { id: 201, text: `The battle is won by persistence.`, author: "Jesse Owens" },
  { id: 202, text: `Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine.`, author: "Wilma Rudolph" },
  { id: 203, text: `The stock market is a device for transferring money from the impatient to the patient.`, author: "Warren Buffett" },
  { id: 204, text: `Pain + reflection = progress.`, author: "Ray Dalio" },
  { id: 205, text: `The moment you give up is the moment you let someone else win.`, author: "Kobe Bryant" },
  { id: 206, text: `Business opportunities are like buses, there's always another one coming.`, author: "Richard Branson" },
  { id: 207, text: `Don't sit down and wait for the opportunities to come. Get up and make them.`, author: "Madam C.J. Walker" },
  { id: 208, text: `You don't have to be perfect to be powerful.`, author: "Michele Obama" },
  { id: 209, text: `We cannot all succeed when half of us are held back.`, author: "Malala Yousafzai" },
  { id: 210, text: `The only way to get out of the darkness is to put one foot in front of the other.`, author: "Margaret Walker" },
  { id: 211, text: `Fall forward.`, author: "Denzel Washington" },
  { id: 212, text: `When you are afraid, do it afraid.`, author: "Morgan Freeman" },
  { id: 213, text: `Live as if you were to die tomorrow; learn as if you were to live forever.`, author: "Mahatma Gandhi" },
  { id: 214, text: `Opportunity is missed by most people because it is dressed in overalls and looks like work.`, author: "Thomas Edison" },
  { id: 215, text: `Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.`, author: "Marianne Williamson" },
  { id: 216, text: `You may not remember what someone said, but you will remember how they made you feel.`, author: "Maya Angelou" },
  { id: 217, text: `Accept whatever comes to you woven in the pattern of your destiny.`, author: "Marcus Aurelius" },
  { id: 218, text: `The future is purchased by the present.`, author: "Seneca" },
  { id: 219, text: `Train yourself to be a master of your mind.`, author: "Epictetus" },
  { id: 220, text: `The soul is a citadel; keep it guarded.`, author: "Marcus Aurelius" },
  { id: 221, text: `We are not born to do just one thing with our lives.`, author: "Seneca" },
  { id: 222, text: `The good man is he who is not swayed by pleasure or pain.`, author: "Epictetus" },
  { id: 223, text: `The true philosopher is not one who shouts, but one who lives by reason.`, author: "Marcus Aurelius" },
  { id: 224, text: `Do not live to be admired by others. Live to be worthy of admiration.`, author: "Seneca" },
  { id: 225, text: `A person becomes expert by learning, not by wishing.`, author: "Epictetus" },
  { id: 226, text: `A man's worth is measured by how he withstands hardships.`, author: "Marcus Aurelius" },
  { id: 227, text: `Life is not a contest of strength but of wisdom.`, author: "Seneca" },
  { id: 228, text: `If you want peace, be rid of your desires.`, author: "Epictetus" },
  { id: 229, text: `The obstacle is not the obstacle. It is the fear of it.`, author: "Marcus Aurelius" },
  { id: 230, text: `The greatest wealth is not to own more, but to need less.`, author: "Seneca" },
  { id: 231, text: `Every action has a purpose; choose the one that aligns with your character.`, author: "Epictetus" },
  { id: 232, text: `There is no reason to be upset by what happens in the world; it is all in motion.`, author: "Marcus Aurelius" },
  { id: 233, text: `A man ought to hold fast to his own path and not be shaken by the noise of the crowd.`, author: "Seneca" },
  { id: 234, text: `Let your will be bound to justice, not to opinion.`, author: "Epictetus" },
  { id: 235, text: `People are disturbed not by the events themselves, but by their judgments about them.`, author: "Marcus Aurelius" },
  { id: 236, text: `What matters is not how much time you have but how you use it.`, author: "Seneca" },
  { id: 237, text: `When a man is in love with his purpose, he will endure any hardship.`, author: "Epictetus" },
  { id: 238, text: `The soul becomes tranquil when it is guided by what is right.`, author: "Marcus Aurelius" },
  { id: 239, text: `The strongest person is not the one who wins every battle, but the one who can stand after the loss.`, author: "Seneca" },
  { id: 240, text: `Be not swayed by the words of the crowd, but by what is true and just.`, author: "Epictetus" },
  { id: 241, text: `You will be judged by your actions, not by your intentions alone.`, author: "Marcus Aurelius" },
  { id: 242, text: `Discipline is not drudgery; it is the path to freedom.`, author: "Seneca" },
  { id: 243, text: `Your mind is your greatest weapon, sharpen it with practice.`, author: "Epictetus" },
  { id: 244, text: `The future depends on what you do today.`, author: "Marcus Aurelius" },
  { id: 245, text: `To be a good man, first be a disciplined one.`, author: "Seneca" },
  { id: 246, text: `Do not let your attention drift toward things that are out of your control.`, author: "Epictetus" },
  { id: 247, text: `We must not allow ourselves to be carried by chance; we must shape our lives with intention.`, author: "Marcus Aurelius" },
  { id: 248, text: `The difficulty is the teacher; endure it, learn from it.`, author: "Seneca" },
  { id: 249, text: `No man is conquered until his mind is conquered.`, author: "Epictetus" },
  { id: 250, text: `A man who is good at making excuses is seldom good at anything else.`, author: "Marcus Aurelius" },
  { id: 251, text: `The wise man will turn pain into wisdom and loss into strength.`, author: "Seneca" },
  { id: 252, text: `Suffer what is necessary, endure, and become stronger.`, author: "Epictetus" },
  { id: 253, text: `The very things which we cannot reach are the things we should be learning most from.`, author: "Marcus Aurelius" },
  { id: 254, text: `Life is a long lesson in humility.`, author: "Seneca" },
  { id: 255, text: `Do not be weary of improving yourself; the work is the reward.`, author: "Epictetus" },
  { id: 256, text: `The first step is to stop blaming the world and look inward.`, author: "Marcus Aurelius" },
  { id: 257, text: `The world is not so much a place as a school for character.`, author: "Seneca" },
  { id: 258, text: `The road to greatness is found in daily, humble effort.`, author: "Epictetus" },
  { id: 259, text: `The man who conquers himself is greater than the one who conquers a city.`, author: "Marcus Aurelius" },
  { id: 260, text: `The wise man does not care for applause, only for the right thing.`, author: "Seneca" },
  { id: 261, text: `Nothing can disturb a man who has mastered his own mind.`, author: "Epictetus" },
  { id: 262, text: `Let your purpose be broad enough to include something greater than yourself.`, author: "Marcus Aurelius" },
  { id: 263, text: `There are no shortcuts to character, only repetition and endurance.`, author: "Seneca" },
  { id: 264, text: `The soul can handle hardship if it is not convinced it is a tragedy.`, author: "Epictetus" },
  { id: 265, text: `Your worth is not determined by the opinions of others.`, author: "Marcus Aurelius" },
  { id: 266, text: `A person who is honest with himself will always have a path forward.`, author: "Seneca" },
  { id: 267, text: `Self-control is the first and greatest victory.`, author: "Epictetus" },
  { id: 268, text: `The power that governs is the power to choose your response.`, author: "Marcus Aurelius" },
  { id: 269, text: `The wise person knows that time is borrowed and should be used well.`, author: "Seneca" },
  { id: 270, text: `Do not think that hardship is an enemy; it is a teacher.`, author: "Epictetus" },
  { id: 271, text: `When you look at the whole of life, you find that what matters is not comfort but meaning.`, author: "Marcus Aurelius" },
  { id: 272, text: `The path of greatness is neither easy nor fast, but it is honest.`, author: "Seneca" },
  { id: 273, text: `Nothing is more valuable than a disciplined mind.`, author: "Epictetus" },
  { id: 274, text: `The best preparation for tomorrow is doing your best today.`, author: "Marcus Aurelius" },
  { id: 275, text: `Listen to your conscience and let it guide your discipline.`, author: "Seneca" },
  { id: 276, text: `Nothing can separate a truly strong man from his principles.`, author: "Epictetus" },
  { id: 277, text: `The things that are not in your control are not worth your distress.`, author: "Marcus Aurelius" },
  { id: 278, text: `In the midst of chaos, a man of principle is the one who remains steady.`, author: "Seneca" },
  { id: 279, text: `A wise person has no need to chase admiration.`, author: "Epictetus" },
  { id: 280, text: `To be yourself is the highest discipline.`, author: "Marcus Aurelius" },
  { id: 281, text: `Even in defeat, the strong man keeps his dignity.`, author: "Seneca" },
  { id: 282, text: `The wise are not conquered by difficulty, only by their own indecision.`, author: "Epictetus" },
  { id: 283, text: `The man who does not know where he is going is lost before he starts.`, author: "Marcus Aurelius" },
  { id: 284, text: `No one becomes powerful by caring too much about what others think.`, author: "Seneca" },
  { id: 285, text: `Character is what you do when your will is tested.`, author: "Epictetus" },
  { id: 286, text: `Aim to be the best version of yourself, not the biggest in the room.`, author: "Marcus Aurelius" },
  { id: 287, text: `The strongest men are not the loudest; they are the most self-commanded.`, author: "Seneca" },
  { id: 288, text: `The purpose of life is not to chase comfort, but to become excellent.`, author: "Epictetus" },
  { id: 289, text: `The time to act is now, even when fear stands in the way.`, author: "Marcus Aurelius" },
  { id: 290, text: `Where there is a will, there is a way; where there is discipline, there is a future.`, author: "Seneca" },
  { id: 291, text: `The mind must be its own master before it can master the world.`, author: "Epictetus" },
  { id: 292, text: `Do not waste your life in vain argument; become a man of focus and action.`, author: "Marcus Aurelius" },
  { id: 293, text: `The wise are not careless; they are deliberate.`, author: "Seneca" },
  { id: 294, text: `Only the disciplined soul can live without fear.`, author: "Epictetus" },
  { id: 295, text: `In the midst of adversity, measure your character, not your comfort.`, author: "Marcus Aurelius" },
  { id: 296, text: `A life without purpose is a life without direction.`, author: "Seneca" },
  { id: 297, text: `A man's greatness lies not in possessions but in command over himself.`, author: "Epictetus" },
  { id: 298, text: `Never let a day pass without improving your mind.`, author: "Marcus Aurelius" },
  { id: 299, text: `The burden of failure is less than the burden of regret.`, author: "Seneca" },
  { id: 300, text: `To be free is to be unshaken by what is outside you.`, author: "Epictetus" },
  { id: 301, text: `The end of diligence is not riches, but self-mastery.`, author: "Marcus Aurelius" },
  { id: 302, text: `Life is not about avoiding pain; it is about learning how to carry it with dignity.`, author: "Seneca" },
  { id: 303, text: `Keep your mind fixed on what is good and necessary.`, author: "Epictetus" },
  { id: 304, text: `If a man is to be worthy, he must act from principle, not impulse.`, author: "Marcus Aurelius" },
  { id: 305, text: `There is no great man who is not also a disciplined man.`, author: "Seneca" },
  { id: 306, text: `No matter how hard the storm, the mind can remain calm in its purpose.`, author: "Epictetus" },
  { id: 307, text: `The real test of character is not who you are under applause, but who you are under pressure.`, author: "Marcus Aurelius" },
  { id: 308, text: `The higher your ambition, the more patience your discipline must have.`, author: "Seneca" },
  { id: 309, text: `A man's dignity comes from his choices, not his circumstances.`, author: "Epictetus" },
  { id: 310, text: `You do not need to be admired to be worthy; you only need to be honest.`, author: "Marcus Aurelius" },
  { id: 311, text: `The man who can face defeat without bitterness is already a victor.`, author: "Seneca" },
  { id: 312, text: `Do not mistake comfort for success; success is built by effort.`, author: "Epictetus" },
  { id: 313, text: `No one can take away your thoughts unless you give them away.`, author: "Marcus Aurelius" },
  { id: 314, text: `It is better to suffer a little now than to live in ruin forever.`, author: "Seneca" },
  { id: 315, text: `The noble life is built through self-command.`, author: "Epictetus" },
  { id: 316, text: `Master your mind and the world will be manageable.`, author: "Marcus Aurelius" },
  { id: 317, text: `The pain of effort is easier to carry than the shame of surrender.`, author: "Seneca" },
  { id: 318, text: `Your purpose is not found in ease but in resolute action.`, author: "Epictetus" },
  { id: 319, text: `A man should not be ashamed to ask for help, but he should never stop striving.`, author: "Marcus Aurelius" },
  { id: 320, text: `The life that is free of sorrow is not the most valuable; the life that is free of fear is.`, author: "Seneca" },
  { id: 321, text: `A strong will is often more valuable than a strong body.`, author: "Epictetus" },
  { id: 322, text: `No man becomes great by being comfortable; he becomes great by rising from hardship.`, author: "Marcus Aurelius" },
  { id: 323, text: `Be tougher than your excuses, and calmer than your emotions.`, author: "Seneca" },
  { id: 324, text: `The wise fully accept what is inevitable and focus on what can be shaped.`, author: "Epictetus" },
  { id: 325, text: `Your character is what remains when all external applause is gone.`, author: "Marcus Aurelius" },
  { id: 326, text: `A disciplined mind turns obstacles into opportunities.`, author: "Seneca" },
  { id: 327, text: `The only real prison is the prison of the mind.`, author: "Epictetus" },
  { id: 328, text: `The world is not asking for your approval; it is asking for your effort.`, author: "Marcus Aurelius" },
  { id: 329, text: `What you become in hidden moments decides the man you are in public.`, author: "Seneca" },
  { id: 330, text: `A person who knows himself will never be easily shaken.`, author: "Epictetus" },
  { id: 331, text: `To live well, first learn to think well.`, author: "Marcus Aurelius" },
  { id: 332, text: `Fortune can take many things, but not the reward of a well-lived life.`, author: "Seneca" },
  { id: 333, text: `The man who lives in truth will not be ruled by opinion.`, author: "Epictetus" },
  { id: 334, text: `Do not let the future terrify you; the future is shaped by the actions you take now.`, author: "Marcus Aurelius" },
  { id: 335, text: `The secret of success is not in speed, but in staying power.`, author: "Seneca" },
  { id: 336, text: `The mind is not conquered by noise, but by clarity.`, author: "Epictetus" },
  { id: 337, text: `The shortest path to wisdom is the willingness to be taught.`, author: "Marcus Aurelius" },
  { id: 338, text: `Work on your soul as relentlessly as you work on your craft.`, author: "Seneca" },
  { id: 339, text: `The good man does not rely on luck to be good.`, author: "Epictetus" },
  { id: 340, text: `The battle for your life is won by your daily habits.`, author: "Marcus Aurelius" },
  { id: 341, text: `Control your appetite and you command your life.`, author: "Seneca" },
  { id: 342, text: `A man should not spend his life chasing what is fleeting.`, author: "Epictetus" },
  { id: 343, text: `Difficulties are opportunities to show what is inside you.`, author: "Marcus Aurelius" },
  { id: 344, text: `A life of no discipline is a life of no direction.`, author: "Seneca" },
  { id: 345, text: `The best men are made in the quiet moments of discipline.`, author: "Epictetus" },
  { id: 346, text: `The way to greatness lies in doing what is right, not what is popular.`, author: "Marcus Aurelius" },
  { id: 347, text: `No one is truly defeated until they stop trying.`, author: "Seneca" },
  { id: 348, text: `What is yours cannot be taken from you if you refuse to surrender it.`, author: "Epictetus" },
  { id: 349, text: `Courage is the power to act when the mind knows the risk.`, author: "Marcus Aurelius" },
  { id: 350, text: `Man is not made for comfort; he is made for purpose.`, author: "Seneca" },
  { id: 351, text: `The soul grows by what it endures when it has chosen its values.`, author: "Epictetus" },
  { id: 352, text: `Your life is a sum of your habits; sharpen them wisely.`, author: "Marcus Aurelius" },
  { id: 353, text: `A disciplined man can stand in any storm without losing his center.`, author: "Seneca" },
  { id: 354, text: `The truth is not found in emotion, but in reason and judgment.`, author: "Epictetus" },
  { id: 355, text: `The effort to improve yourself is the foundation of success.`, author: "Marcus Aurelius" },
  { id: 356, text: `They are not master of life who are ruled by their impulses.`, author: "Seneca" },
  { id: 357, text: `The man who chooses virtue chooses his own greatness.`, author: "Epictetus" },
  { id: 358, text: `Call yourself fortunate because you are still able to learn.`, author: "Marcus Aurelius" },
  { id: 359, text: `A man's life is shaped by what he refuses to ignore.`, author: "Seneca" },
  { id: 360, text: `The disciplined body listens to the disciplined mind.`, author: "Epictetus" },
  { id: 361, text: `The highest art is the art of living well.`, author: "Marcus Aurelius" },
  { id: 362, text: `The wise man does not flee pain; he learns to carry it without being owned by it.`, author: "Seneca" },
  { id: 363, text: `A calm mind is stronger than a turbulent world.`, author: "Epictetus" },
  { id: 364, text: `You will never be truly free if your thinking is enslaved by others.`, author: "Marcus Aurelius" },
  { id: 365, text: `Character is built in the repetition of small acts of courage.`, author: "Seneca" }
];

function{
     
}